/*
 * VeCoDis Command Endpoints
 *
 * This service offers the capability for external systems to inject commands into the VeCoDis Context
 *
 * OpenAPI spec version: 0.0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System.Runtime.Serialization;
using System.Text;

namespace M5x.CEQS.Schema.Common
{
    public record Latitude
    {
        public enum NsEnum
        {
            /// <summary>
            ///     Enum NEnum for N
            /// </summary>
            [EnumMember(Value = "N")] NEnum = 0,

            /// <summary>
            ///     Enum SEnum for S
            /// </summary>
            [EnumMember(Value = "S")] SEnum = 1
        }

        public int? Degrees { get; set; }
        public int? Minutes { get; set; }
        public decimal? Seconds { get; set; }

        public NsEnum? Ns { get; set; }

        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Latitude {\n");
            sb.Append("  Degrees: ").Append(Degrees).Append("\n");
            sb.Append("  Minutes: ").Append(Minutes).Append("\n");
            sb.Append("  Seconds: ").Append(Seconds).Append("\n");
            sb.Append("  Ns: ").Append(Ns).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
    }
}